
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    environment:
      - NODE_ENV=development
    working_dir: /workspace
    user: node
    tty: true
    ports:
      - '8070:8070'
      - '8071:8071'
