
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    working_dir: /workspace
    user: node
    tty: true
    ports:
      - '8070:8070'
      